BulkyWeb/Areas/Admin/Controllers/CategoryController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Category> objCategoryList = _unitOfWork.Category.GetAll().ToList();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "Category Name cannot be the same as Display Order");
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? objCategory = _unitOfWork.Category.Get(c => c.Id == id);
            if (objCategory == null)
            {
                return NotFound();
            }
            return View(objCategory);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "Category Name cannot be the same as Display Order");
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? objCategory = _unitOfWork.Category.Get(c => c.Id == id);
            if (objCategory == null)
            {
                return NotFound();
            }
            return View(objCategory);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Category? objCategory = _unitOfWork.Category.Get(c => c.Id == id);
            if (objCategory == null)
            {
                return NotFound();
            }

            _unitOfWork.Category.Remove(objCategory);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Diagnostics;
using System.Security.Claims;

namespace BulkyWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize]
	public class OrderController : Controller
	{
		public readonly IUnitOfWork _unitOfWork;
		[BindProperty]
		public OrderVM OrderVM { get; set; }

		public OrderController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Details(int orderId)
		{
			OrderVM = new()
			{
				OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includedProperties: "ApplicationUser"),
				OrderDetail = _unitOfWork.OrderDetail.GetAll(u => u.OrderHeaderId == orderId, includedProperties: "Product")
			};
			return View(OrderVM);
		}

		[HttpPost]
		[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
		public IActionResult UpdateOrderDetail()
		{
			var orderHeaderFromDB = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
			orderHeaderFromDB.Name = OrderVM.OrderHeader.Name;
			orderHeaderFromDB.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
			orderHeaderFromDB.StreetAddress = OrderVM.OrderHeader.StreetAddress;
			orderHeaderFromDB.City = OrderVM.OrderHeader.City;
			orderHeaderFromDB.State = OrderVM.OrderHeader.State;
			orderHeaderFromDB.PostalCode = OrderVM.OrderHeader.PostalCode;
			if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
			{
				orderHeaderFromDB.PostalCode = OrderVM.OrderHeader.PostalCode;
			}
			if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
			{
				orderHeaderFromDB.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
			}

			_unitOfWork.OrderHeader.Update(orderHeaderFromDB);
			_unitOfWork.Save();

			TempData["Success"] = "Order Details Updated Successfully.";

			return RedirectToAction(nameof(Details), new { orderId = orderHeaderFromDB.Id });
		}

		[HttpPost]
		[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
		public IActionResult StartProcessing()
		{
			_unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.Status_InProcess);
			_unitOfWork.Save();

			TempData["Success"] = "Order Started Processing Successfully.";

			return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
		}

		[HttpPost]
		[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
		public IActionResult ShipOrder()
		{
			_unitOfWork.OrderHeader.UpdateShippingStatus(OrderVM.OrderHeader.Id, OrderVM.OrderHeader.Carrier, OrderVM.OrderHeader.TrackingNumber);
			_unitOfWork.Save();

			TempData["Success"] = "Order Shipped Successfully.";

			return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
		}

		[HttpPost]
		[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
		public IActionResult CancelOrder()
		{
			var orderHeaderFromDB = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);

			if(orderHeaderFromDB.PaymentStatus == SD.PaymentStatus_Approved)
			{
				var options = new RefundCreateOptions()
				{
					Reason = RefundReasons.RequestedByCustomer,
					PaymentIntent = orderHeaderFromDB.PaymentIntentId
				};

				var service = new RefundService();
				Refund refund = service.Create(options);

				_unitOfWork.OrderHeader.UpdateStatus(orderHeaderFromDB.Id, SD.Status_Cancelled, SD.Status_Refunded);
			}
			else
			{
				_unitOfWork.OrderHeader.UpdateStatus(orderHeaderFromDB.Id, SD.Status_Cancelled, SD.Status_Cancelled);
			}
			_unitOfWork.Save();

			TempData["Success"] = "Order Cancelled Successfully.";

			return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
		}

		[ActionName("Details")]
		[HttpPost]
		public IActionResult Details_PAY_NOW()
		{
			OrderVM.OrderHeader = _unitOfWork.OrderHeader.Get(u=> u.Id == OrderVM.OrderHeader.Id, includedProperties:"ApplicationUser");
			OrderVM.OrderDetail = _unitOfWork.OrderDetail.GetAll(u => u.OrderHeaderId == OrderVM.OrderHeader.Id, includedProperties: "Product");

			//its a company account and who needs to pay
			//stripe logic
			var domain = Request.Scheme + "://" + Request.Host.Value + "/";
			var options = new SessionCreateOptions
			{
				SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderHeaderId={OrderVM.OrderHeader.Id}",
				CancelUrl = domain + $"admin/order/details?orderHeaderId={OrderVM.OrderHeader.Id}",
				LineItems = new List<SessionLineItemOptions>(),
				Mode = "payment",
			};

			foreach (var item in OrderVM.OrderDetail)
			{
				var sessionItem = new SessionLineItemOptions
				{
					PriceData = new SessionLineItemPriceDataOptions()
					{
						UnitAmount = (long)(item.Price * 100),
						Currency = "brl",
						ProductData = new SessionLineItemPriceDataProductDataOptions()
						{
							Name = item.Product.Title,
						}
					},
					Quantity = item.Count
				};
				options.LineItems.Add(sessionItem);
			}

			var service = new SessionService();
			Session session = service.Create(options);
			_unitOfWork.OrderHeader.UpdateStripePaymentId(OrderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
			_unitOfWork.Save();

			Response.Headers.Add("Location", session.Url);
			return new StatusCodeResult(303);
		}

		public IActionResult PaymentConfirmation(int orderHeaderId)
		{
			OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderHeaderId);
			if (orderHeader.PaymentStatus == SD.PaymentStatus_DelayedPayment)
			{
				//this is an order by company
				var service = new SessionService();
				Session session = service.Get(orderHeader.SessionId);
				if (session.PaymentStatus.ToLower() == "paid")
				{
					_unitOfWork.OrderHeader.UpdateStripePaymentId(orderHeaderId, session.Id, session.PaymentIntentId);
					_unitOfWork.OrderHeader.UpdateStatus(orderHeaderId, orderHeader.OrderStatus, SD.PaymentStatus_Approved);
					_unitOfWork.Save();
				}
			}

			return View(orderHeaderId);
		}

		#region APICALLS

		[HttpGet]
		public IActionResult GetAll(string status)
		{
			IEnumerable<OrderHeader> objOrderHeaders;

			if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
			{
				objOrderHeaders = _unitOfWork.OrderHeader.GetAll(includedProperties: "ApplicationUser").ToList();
			}
			else
			{
				var claimsIdentity = (ClaimsIdentity)User.Identity;
				var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

				objOrderHeaders = _unitOfWork.OrderHeader.GetAll(u => u.ApplicationUserId == userId, includedProperties: "ApplicationUser").ToList();
			}

			switch (status)
			{
				case "inprocess":
					objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatus == SD.Status_InProcess);
					break;
				case "pending":
					objOrderHeaders = objOrderHeaders.Where(u => u.PaymentStatus == SD.PaymentStatus_Pending);
					break;
				case "completed":
					objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatus == SD.Status_Shipped);
					break;
				case "approved":
					objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatus == SD.Status_Approved);
					break;
				default:
					break;
			}

			return Json(new { data = objOrderHeaders });
		}

		#endregion
	}
}

BulkyWeb/Areas/Admin/Controllers/UserController.cs
using Bulky.DataAccess.Data;
using Bulky.DataAccess.Repository;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RoleManagement(string id)
        {
            UserVM userVM = new()
            {
                ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == id),
                CompaniesList = _unitOfWork.Company.GetAll(),
                RolesList = _roleManager.Roles.ToList()
            };

            userVM.ApplicationUser.Role = _userManager.GetRolesAsync(userVM.ApplicationUser)
                .GetAwaiter().GetResult().FirstOrDefault();

            return View(userVM);
        }

        [HttpPost]
        public IActionResult RoleManagement(UserVM userVM)
        {
            var userObj = _unitOfWork.ApplicationUser.Get(u => u.Id == userVM.ApplicationUser.Id, tracked: true);

            string oldRoleName = _userManager.GetRolesAsync(userObj).GetAwaiter().GetResult().FirstOrDefault();

            if (oldRoleName == userVM.ApplicationUser.Role && userObj.CompanyId == userVM.ApplicationUser.CompanyId)
            {
                userVM.CompaniesList = _unitOfWork.Company.GetAll();
                userVM.RolesList = _roleManager.Roles.ToList();
                TempData["error"] = "Role did not change";
                return View(userVM);
            }
            
            if (oldRoleName != userVM.ApplicationUser.Role)
            {
                _userManager.RemoveFromRoleAsync(userObj, oldRoleName).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(userObj, userVM.ApplicationUser.Role).GetAwaiter().GetResult();
            }

            if (oldRoleName == SD.Role_Company)
            {
                _unitOfWork.ApplicationUser.UpdateCompany(userObj.Id, null);
            }

            if (userVM.ApplicationUser.Role == SD.Role_Company)
            {
                _unitOfWork.ApplicationUser.UpdateCompany(userObj.Id, userVM.ApplicationUser.CompanyId);
            }
            
            _unitOfWork.Save();

            TempData["success"] = "User Role changed successfully";
            return RedirectToAction("Index");
        }

        #region API CLASS

        [HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<ApplicationUser> objUserList = _unitOfWork.ApplicationUser.GetAll(includedProperties: "Company");

            foreach (var objUser in objUserList)
            {
                objUser.Role = _userManager.GetRolesAsync(objUser).GetAwaiter().GetResult().FirstOrDefault();

                if (objUser.Company == null)
                {
                    objUser.Company = new() { Name = "" };
                }
            }

            return Json(new { data = objUserList });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody] string id)
        {
            var objFromdb = _unitOfWork.ApplicationUser.Get(u => u.Id == id);
            if (objFromdb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }

            if (objFromdb.LockoutEnd != null && objFromdb.LockoutEnd > DateTime.Now)
            {
                //user is currently locked and we need to unlock
                _unitOfWork.ApplicationUser.UnlockUser(objFromdb.Id);
            }
            else
            {
                _unitOfWork.ApplicationUser.LockUser(objFromdb.Id);
            }

            _unitOfWork.Save();
            return Json(new { success = true, message = "Locking/Unlocking Successfull" });
        }

        #endregion
    }
}

BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyWeb.ViewComponents
{
	public class ShoppingCartViewComponent : ViewComponent
	{
		private readonly IUnitOfWork _unitOfWork;
		public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var claimsIdentity = User.Identity as ClaimsIdentity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			if (claim != null)
			{
				var cartCount = HttpContext.Session.GetInt32(SD.SessionCart);
				if(cartCount == null)
				{
					HttpContext.Session.SetInt32(SD.SessionCart,
						_unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).Count());
					cartCount = HttpContext.Session.GetInt32(SD.SessionCart);
				}

				return View(cartCount);
			}

			HttpContext.Session.Clear();
			return View(0);
		}
	}
}

BulkyWeb/Views/Shared/_Layout.cshtml
@*@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
	var cartCount = HttpContextAccessor.HttpContext.Session.GetInt32(SD.SessionCart);
	if (cartCount == null)
	{
		cartCount = 0;
	}
}*@

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - BulkyWeb</title>
	<link rel="icon" href="/images/book.png">
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	<link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
	<link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
					<img src="/images/book.png" style="width:30px" />
				</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav auto">
						<li class="nav-item">
							<a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
						</li>
						@if(User.IsInRole(SD.Role_Admin)){
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Dropdown
								</a>
								<ul class="dropdown-menu">
									<li class="nav-item">
										<a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
									</li>
									<li class="nav-item">
										<a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
									</li>
									<li class="nav-item">
										<a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
									</li>
									<li><hr class="dropdown-divider"></li>
									<li class="nav-item">
										<a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
									</li>
									<li class="nav-item">
										<a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
									</li>
								</ul>
							</li>
						}
						<li class="nav-item">
							<a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
								@await Component.InvokeAsync("ShoppingCart")
							</a>
						</li>
					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			<partial name="_Notification" />
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer bg-primary text-white-50">
		<div class="text-center">
			Made with <i class="bi bi-heart-fill"></i> by Mathews Alves
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.tiny.cloud/1/x2tmyn8r703ilyxo6n5q54ygq1v5nw1q6aowpplfupww8fxh/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}

@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData["error"]');
	</script>
}